### ISSUE TITLE
Can't read a single line

### ISSUE THREAD

**Issue by spaghetti-** [wjwwood/serial#63]
My board is spitting out lines separated by "\r\n" at an arbitrary refresh rate x Hz.

I can't seem to read data line by line and flush() doesn't work.

Any idea how to use it?

**Comment by wjwwood** [comment]
So, looking at this again, the issue is that `readline(data)` will get up to the next delimiter, but then you are doing `flush()` which will drop any other data already in the queue:

https://github.com/wjwwood/serial/blob/master/include/serial/serial.h#L554-L556

The reason being that it flushes the output as well as the input and the input flush ends up doing this:

https://github.com/wjwwood/serial/blob/master/src/impl/unix.cc#L798
```c++
tcflush (fd_, TCIFLUSH);
```

Which does drop data that has been received but not read:

http://pubs.opengroup.org/onlinepubs/7908799/xsh/tcflush.html
> If queue_selector is TCIFLUSH it flushes data received but not read.

I would use something like this:

```c++
string serialRead(serial::Serial *dev, FILE* f)
{
    string data;
    data = dev->read(dev->available());
    printf(f, "%s", data.c_str());
}
```

Please comment if you have anything else to add.
